apiVersion: v1
kind: Secret
metadata:
  name: master-connection-string
  namespace: ${CONTAINER_LABEL}-ns
type: Opaque
data:
  MASTER_CONNECTION_STRING: <insert-base64-encoded-sql-db-connection-string>

---

apiVersion: v1
kind: Secret
metadata:
  name: atlas-connection-string
  namespace: ${CONTAINER_LABEL}-ns
type: Opaque
data:
  ATLAS_CONNECTION_STRING: <insert_mongodb-connection-string>

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-api-key
  namespace: ${CONTAINER_LABEL}-ns
type: Opaque
data:
  GRAFANA_API_KEY: <insert-grafana-api-key>
